version: '3.1'

services:

 
  scheduler:
    build:
      context: ./base
      dockerfile: Dockerfile
    image: kaj011/dask

    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

    hostname: dask-scheduler
    ports:
      - "8786:8786"
      - "8787:8787"
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - webnet
    command: ["dask-scheduler"]

  notebook:
    build:
      context: ./notebook
      dockerfile: Dockerfile
    image: kaj011/dask-notebook
    hostname: notebook
    ports:
      - "8888:8888"
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - webnet

  worker:
    build:
      context: ./base
      dockerfile: Dockerfile
    image: daskdev/dask
    hostname: dask-worker
    deploy:
      mode: global
    networks:
      - webnet
    command: ["dask-worker scheduler:8786"]

networks:
  webnet:
